### ISSUE TITLE
Does not implement full API defined by atom-id-ui datatips

### ISSUE THREAD

**Issue by lloiser** [atom-community/atom-ide-datatip#1]
The datatip service defined in atom-ide-ui surfaces more functions that are currently not implemented here and cause atom to show an error notification:

```js
export type DatatipService = {
  addProvider(provider: DatatipProvider): IDisposable,
  addModifierProvider(provider: ModifierDatatipProvider): IDisposable,
  createPinnedDataTip(
    datatip: Datatip,
    editor: TextEditor,
    options?: PinnedDatatipOptions,
  ): IDisposable,
};
```
Service definition in atom-ide-ui:
https://github.com/facebookarchive/atom-ide-ui/blob/710f8477607d3788aeadcbdd55079925241ce40d/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/types.js#L18-L26

Usage: 
https://github.com/facebookarchive/atom-ide-ui/blob/710f8477607d3788aeadcbdd55079925241ce40d/modules/atom-ide-ui/pkg/atom-ide-definitions/lib/main.js#L256-L270

**Comment by appelgriebsch** [comment]
I rather followed along the definition of the Atom-LanguageClient package actively maintained by the Atom folks...

`
  export interface DatatipService {
    addProvider(provider: DatatipProvider): Disposable;
  }
`

https://github.com/atom/atom-languageclient/blob/master/typings/atom-ide/index.d.ts#L114-L138
