### ISSUE TITLE
After toggling datatip with keybinding (cmd+alt), datatips appear on mouse hover, even if disabled in settings

### ISSUE THREAD

**Issue by jonboiser** [atom-community/atom-ide-datatip#118]
I'm actually experiencing the same issue as #54, but am running the most recent version of this library (0.23.2). I have:

1. Disabled datatips when hovering with mouse and keyboard.
2. When I am in a new buffer (with Python code), I get no datatips when hovering over symbols with my mouse.
3. When I activate the "datatip:toggle" command with my keyboard, the datatip will appear over my caret.
4. When I toggle it again, the datatip will disappear, but now datatips will appear when I hover with my mouse (the issue in #54).

Here is a video, starting with a new buffer of Python code (the workaround described in #54). I start out getting no datatips on hovering, but after typing cmd+alt, they appear when I mouse-hover:

![CleanShot 2021-02-09 at 13 03 51](https://user-images.githubusercontent.com/10248067/107428516-99749780-6ad7-11eb-862d-dbd018e7a1f3.gif)

**Comment by clberube** [comment]
I'm experiencing the same issue. I'd like to add that the `Hover/Stay Time` option has no effect and the datatip shows up instantly regardless of the value entered after pressing `alt+cmd`. 
Uninstalling the package seems to be the way to go for now. The tooltips are constantly obstructing the code.

**Comment by aminya** [comment]
The default config changed recently to match other IDEs such as Visual Studio, VSCode, etc. Now, on mouse hover the datatips are shown. 

But if you disable mouse hover in the settings, datatips should not appear on mouse hover. If they still do, that is a bug.
