### ISSUE TITLE
datatip cuts (...) content 

### ISSUE THREAD

**Issue by lloiser** [atom-community/atom-ide-datatip#15]
given the following datatip

```js
{
  grammar: ... // a valid atom grammar
  type: "snippet",
  value: "(path: string) => string"
}
```

The datatip only shows

![image](https://user-images.githubusercontent.com/3003233/51791483-1dcf7880-21a4-11e9-836b-0b5dbd578791.png)

Related code:
https://github.com/appelgriebsch/atom-ide-datatip/blob/9c364d7c35072f6fb24b502f7ae4219406cb72e4/lib/datatip-view.js#L27-L30
Why does this code exist?

**Comment by appelgriebsch** [comment]
Hey, some language server start the snippets with something like this:
```
(method) SnippetView.refreshRootElement(snippet: any, grammar: any): void
```

and I use this if-statement to filter out the initial semantic hint. In the early days (until we have had syntax colouring in place via atom-text-editor) I was replacing this semantic hint with a corresponding icon:

```
const TYPE_TO_ICON_NAME = {
  array: 'type-array',
  boolean: 'type-boolean',
  class: 'type-class',
  constant: 'type-constant',
  constructor: 'type-constructor',
  enum: 'type-enum',
  field: 'type-field',
  file: 'type-file',
  function: 'type-function',
  interface: 'type-interface',
  method: 'type-method',
  module: 'type-module',
  namespace: 'type-namespace',
  number: 'type-number',
  package: 'type-package',
  property: 'type-property',
  string: 'type-string',
  variable: 'type-variable',
};

```

So definitely have to refine this if-statement....

**Comment by appelgriebsch** [comment]
started with an initial regexp to filter the most common prefixes: method, parameter, property. Can be extended later if needed.
