### ISSUE TITLE
What other packages need to be installed beside this?

### ISSUE THREAD

**Issue by ryanolsonx** [atom-community/atom-ide-datatip#17]
I installed this package and have been trying to use it. What do I need to install in order for it to work? simply the `ide-{language}` package? Or does it *need* `atom-ide-ui`? It would be awesome to avoid installing that.

**Comment by appelgriebsch** [comment]
Hey,

its a complete 'drop-in' replacement for the datatip functionality of the atom-ide-ui package. So you don't need to install this one. Still it relies on the functionality of the language server to deliver the content; so you will need language-specific ide-... packages (such as ide-typescript, ide-go, ide-rust, ...). Most of these will ask to install the atom-ide-ui package on your behalf. This you will have to deny.

**Comment by ryanolsonx** [comment]
Awesome. Maybe something should be added to the README to communicate that you'd need a language package in order for this package to function. I'll do the same to my https://github.com/ryanolsonx/atom-ide-definitions package. 👍
