### ISSUE TITLE
Shared package styles

### ISSUE THREAD

**Issue by vinkla** [atom-community/atom-ide-datatip#29]
Since both packages `atom-ide-datatip` and `atom-ide-signature-help` are using the same LESS styles we are currently facing some issues:

- The DX (developer experience) currently includes copy/paste between repositories.
- If someone tries to change the packages styles in Atom's developer tools they have to modify the styles for each package before they see their change.
- ~~The packages overrides each other depending on which loads first/last.~~ (solved by [ff1c2cd](https://github.com/atom-ide-community/atom-ide-signature-help/commit/e2f6df4597ca49b51a302e157fa98b22044bbd17))

Here is a list of possible solutions:

1. Releasing the styles as it's own npm package. 
1. Releasing the styles as it's own Atom package. 
1. Move the styles into the `atom-ide-markdown-service` package.
1. Make `atom-ide-signature-help` a dependency of `atom-ide-datatip` or vice versa.

**Comment by appelgriebsch** [comment]
Each implementation uses it’s own styles since a couple of weeks. Ideally you would like to be able to adapt the style of them independently. 

Close this issue.
