### ISSUE TITLE
Today's update looks like this

### ISSUE THREAD

**Issue by linjialiang** [atom-community/atom-ide-datatip#30]
![Snipaste_2019-03-18_15-32-40](https://user-images.githubusercontent.com/8848263/54513692-1e5de180-4993-11e9-806c-9a4b2c80973d.png)

**Comment by linjialiang** [comment]
> 而且非常慢

**Comment by linjialiang** [comment]
> And it was very slow

**Comment by vinkla** [comment]
I can confirm the issue. I'm seeing datatip elements sticking in the viewport.

**Comment by appelgriebsch** [comment]
OK, I guess it's a regression from introducing the markdown rendering service, which is given me a promise with the resulting html data tip. So if things are a little slow on the LSP site it might result in a delayed execution of the markdown rendering, which itself can lead to this issue. Will investigate...

**Comment by linjialiang** [comment]
> Thank you very much !
