### ISSUE TITLE
PHP package support is poor

### ISSUE THREAD

**Issue by linjialiang** [atom-community/atom-ide-datatip#41]
> PHP package support is poor, can you improve it

I use `ide-php`

![图片](https://user-images.githubusercontent.com/8848263/55449967-3e7ed900-5600-11e9-911b-d50503767f18.png)

**Comment by appelgriebsch** [comment]
As this is not related to the data tip component you should check with the ide-php package repo first. When doing so you should notice an issue describing your problem and a potential workaround: https://github.com/atom/ide-php/issues/134

Close issue here.
