### ISSUE TITLE
Does not support grammars with spaces in their names

### ISSUE THREAD

**Issue by mcous** [atom-community/atom-ide-datatip#43]
First off, thanks for putting together this project! I'm happy that y'all are continuing work on language server UI in atom.

I've been trying to get this to work with Flow, and ran into some problems that *prevent datatips from displaying at all*.

My apologies if I'm misunderstanding anything from reading/poking at the code. Here's what I've got:

- atom-ide-datatip takes `grammar.name` and puts it in a DOM class of the datatip `<code>` snippet
    - According to the [Atom docs](https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/#basic-fields), a name with spaces is valid
    - Class names with spaces are *not valid*
    - The name of the Flow tree-sitter grammar is "Flow JavaScript"
    - Accordingly, `DatatipManager::getSnippetHtml` errors out on hover:
    ```
    DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided
    ('flow javascript') contains HTML space characters, which are not valid in tokens
    ```
- If you work around that issue (e.g. replacing all spaces with underscores before adding it to the classList)
    - atom-ide-markdown-service attempts to read the grammar `name` out of the class if the class is present rather than deferring to `grammar` passed in to `highlightCodeFragments`
    - It tries to map that `name` to an editor source via `lib/utils.js` to pass to `atom.grammars.assignLanguageMode`

I'd like to open a PR (or two) to fix this up, and I'd be curious to hear what your thoughts are for the correct solution. I don't know all the implications of the different classNames that get added (e.g. I don't know what the `lang-...` class [here](https://github.com/atom-ide-community/atom-ide-markdown-service/blob/master/lib/renderer.js#L40) is for), but it seems to me that:

- `grammar.name` may not be the best grammar identifier to use, since it's purpose is "A human readable name for the language." (again from the atom docs)
- A DOM className may not be the best mechanism to pass grammar information around

I'm thinking that rather than `grammar.name`, atom-ide-datatip should grab the grammar scope (e.g. `const grammar = editor.getGrammar().scopeName;`) rather than the name. `scopeName` is described as "A unique, stable identifier for the language." Also, I think atom-ide-datatip should add the scope name to a data attribute rather than the className (e.g. `data-scope`)

What do you think?

P.S. In the meantime, I have a very dirty workaround:

```js
// lib/datatip-manager.js

async getSnippetHtml(snippets, grammarName) {
  // ...
      codeElem.classList.add(grammarName.split(' ')[0]);
  // ...
}
```

**Comment by ryanvade** [comment]
Same here:
`DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('vue component') contains HTML space characters, which are not valid in tokens.`
