### ISSUE TITLE
Unmount the datatip right after the focus is removed

### ISSUE THREAD

**Issue by remagpie** [atom-community/atom-ide-datatip#44]
When I move my mouse cursor out of the variable, the datatip is unmounted after a little bit of delay.
From my experience of using `atom-ide-ui` package, I felt it much better when the datatip was removed right after the mouse got out of the variable.
It would be really nice if `atom-ide-datatip` also implement this behavior.

**Comment by remagpie** [comment]
It's been quite a long time since I posted this issue, and now I'm interested in implementing it.
Are you accepting PRs for this? @Belar

**Comment by Belar** [comment]
Thanks for reaching out. Of course, for what I know, no one is working on it and PR will be welcome.

Before labelling, I took a look at the issue and the unmount delay is an effect of [the debounce ("move timer") for mouse event](https://github.com/atom-ide-community/atom-ide-datatip/blob/master/lib/datatip-manager.js#L275) (cursor has one too). I hope it will save you some time and help with the start.

**Comment by aminya** [comment]
This issue is resolved in https://github.com/atom-ide-community/atom-ide-datatip/pull/61
