### ISSUE TITLE
Not showing correctly 

### ISSUE THREAD

**Issue by aminya** [atom-community/atom-ide-datatip#57]
Atom IDE data tips are not shown correctly using this new package:
- [x] No syntax highlighting 
- [x] No formatting, syntax highlighting, line breaks for `jsdoc` docstrings
- [x] The color of datatip matches the editor's background color, which makes it hard to distinguish the two (in One-dark). The datatip can optionally have a border.
- [x] A very small font that is hard to read
- [ ] No pinning option

### Examples using IDE TypeScript:

# atom-ide-datatip
![image](https://user-images.githubusercontent.com/16418197/78344021-582f6500-7561-11ea-9b1f-b2c92223d57e.png)
![image](https://user-images.githubusercontent.com/16418197/78344485-118e3a80-7562-11ea-8762-c1729edb458b.png)

# atom-ide-ui:
![image](https://user-images.githubusercontent.com/16418197/78344086-79905100-7561-11ea-853a-34f9d86645ea.png)

![image](https://user-images.githubusercontent.com/16418197/78344319-d68c0700-7561-11ea-8c6b-8c00e041c1fb.png)

**Comment by Belar** [comment]
Hi,
thanks for the report and including screenshots.

Screenshots for reference:
theme: Atom's `One Dark` (UI and syntax)
code:  `atom-languageclient` package
language server: `ide-typescript` package

`config.get`:
![datatip_one_dark](https://user-images.githubusercontent.com/5208717/78505208-32c57580-7772-11ea-8f22-a8cf3b4382ac.jpg)

`definitions.getDefinition`:
![datatip_docstring_one_dark](https://user-images.githubusercontent.com/5208717/78505450-e2e7ae00-7773-11ea-9ab2-60d17a4d831f.jpg)

> No syntax highlighting

Code highlight seems to be available. However, I did get incorrect formatting, compared to yours.

> No formatting, syntax highlighting, line breaks for jsdoc docstrings

In the first case, both descriptions look as expected (single sentence in italic). However, second pair of your screenshots are showing italicised markdown, for both `atom-ide-datatip` and `atom-ide-ui`. I don't know what is the cause, may be environment related.

> The color of datatip matches the editor's background color, which makes it hard to distinguish the two (in One-dark). The datatip can optionally have a border.

Are you running Atom's default One Dark theme or a flavour? From what I checked, data tip and description have different backgrounds (lighter, darker) and entire tooltip has a hard shadow to contrast with editor - all based on theme. Overall style sheets look true to the original, `atom-ide-ui`.

Adding a light border to the tooltip sounds good, should help in dark themes, where shadow is not enough.

> A very small font that is hard to read

I pushed [a branch](https://github.com/atom-ide-community/atom-ide-datatip/tree/fix-fixed-data-tip-font-size) with a potential fix, makes it respect UI theme's font size setting. However, it wouldn't change anything for default setup, would be great if you could check if it works for the reported case.

> No pinning option

Yes, a missing feature. I'm not sure how popular it is, never used/needed it myself, but could be added.

**Comment by aminya** [comment]
Why your screenshots look so different than mine?⁉️ Yours has two different sections (lighter and darker one). 

Yes I am using default One Dark theme. My Syntax was Atom Dark, but changing to One Dark doesn't change the look of the pup ups.
One-Dark Syntax and Theme:
![image](https://user-images.githubusercontent.com/16418197/78626989-f53a1880-7855-11ea-9bd5-06271d61a638.png)

**Comment by Belar** [comment]
Do you have other package(s) with datatip tooltip functionality installed, or one that could interfere? If yes, maybe there is a conflict, could you try disabling `atom-ide-datatip`?

**Comment by aminya** [comment]
After disabling:
![image](https://user-images.githubusercontent.com/16418197/78865894-1476a880-7a04-11ea-92ad-cf6cad64807c.png)

Which package is this?

**Comment by Belar** [comment]
> Which package is this?

Must be some other datatip provider. The simplest way to find out, that I know of, is to go through your installed packages and play with disabling.

**Comment by artarf** [comment]
Maybe this happens because `main.js` initializes datatip manager before markdown service is initialized. I had similar problem and fixed it by forcing renderer:
```
   consumeMarkdownRenderer(renderer) {
     this.renderer = renderer;
+    this.datatipManager.renderer = renderer;
   }
```

**Comment by aminya** [comment]
I will close this since most of the issues are resolved in the last version as I checked with atom-typescript, ide-typescript, ide-python.
