### ISSUE TITLE
Capability of copying text from inside the datatip

### ISSUE THREAD

**Issue by aminya** [atom-community/atom-ide-datatip#60]
The text inside datatip should be selectable, so people can copy it.

**Comment by aminya** [comment]
I could not make this work by using 
```less
pointer-events: all; // hyperlinks will work
user-select: text;   // allow selecting text // TODO does not work
```

https://github.com/atom-ide-community/atom-ide-datatip/blob/3562cca6c4c43ad21041005b2ed0d41fd9200c79/styles/atom-ide-datatips.less#L12-L13

**Comment by tomas1971** [comment]
#101

**Comment by aminya** [comment]
Juno's datatips are selectable. 
https://github.com/JunoLab/atom-ink/blob/master/lib/editor/result-view.js


Here is the PR that they added this:
https://github.com/JunoLab/atom-ink/pull/239/files

I have not found how we can do it for atom-ide-datatips.

cc: @pfitzseb

**Comment by pfitzseb** [comment]
IIRC you need [to set `tabIndex` to `-1`](https://github.com/JunoLab/atom-ink/blob/87378d40a74cd83790d47971548b8d161095d805/lib/editor/result-view.js#L65) to make decorations selectable. The PR linked above "only" handles focus issues -- just *clicking* on a datatip shouldn't move focus away from the editor, while selecting text should.

**Comment by aminya** [comment]
@pfitzseb Thanks! Setting `tabIndex` makes the text selectable. But I cannot still copy the text. Is there a hack for that one too?


#110 

![datatip](https://user-images.githubusercontent.com/16418197/106628739-bb9e7080-653f-11eb-888c-f38a982668f2.gif)

**Comment by aminya** [comment]
I added a manual CTRL+C listener. Let me know if there is a better way for copying text

**Comment by pfitzseb** [comment]
It should be enough to force browser-native handling for Ctrl-C/Cmd-C on those elements like [here](https://github.com/JunoLab/atom-ink/blob/87378d40a74cd83790d47971548b8d161095d805/keymaps/ink.cson#L11-L15), but I may be misremembering.

**Comment by aminya** [comment]
Thanks, for the tip. I made a function to handle everything.

https://github.com/atom-community/atom-ide-base/blob/c70c863fe76bea2d630541e767916c5af80e1fdc/src-commons-ui/float-pane/selectable-overlay.ts#L7
