### ISSUE TITLE
[Internal] Using only etch 

### ISSUE THREAD

**Issue by aminya** [atom-community/atom-ide-datatip#68]
Current code uses `ReactDOMServer.renderToStaticMarkup` to convert `etch.dom()` return to string and then assign it to the innerHTML. This isn't the best approach for rendering these. We should either use etch or React. Loading both packages degrades the performance.

https://github.com/atom-ide-community/atom-ide-datatip/blob/263a48d6afee3ae918b8588af1dbb66ff243698a/lib/datatip-view.js#L85-L92

**Comment by Belar** [comment]
Agreed, we could streamline rendering a bit. Structure seems small enough to ditch libs entirely, but since most of it sits in Etch already, then maybe we should go with that. What do you think?

**Comment by aminya** [comment]
Yes. We should write the code using only Etch here. Etch is lightweight and suitable for this project.

Instead of converting the react element to string, put the element directly.

**Comment by aminya** [comment]
Doing an analysis of `package.json`, we see that `react-dom` can really slow down this package. 

Fortunately, in #67, I bundled and treeshaked these, so loading time is actually 13ms.

However, still dropping `react` and `react-dom` can have a huge bump in the performance, and we can bring this near 6ms:

![image](https://user-images.githubusercontent.com/16418197/80358093-82fb9900-8841-11ea-9f54-91af7d9ae4b7.png)


https://bundlephobia.com/scan-results?packages=atom-package-deps@5.1.0,dompurify@2.0.8,etch@0.14.0,react@16.13.1,react-dom@16.13.1
![image](https://user-images.githubusercontent.com/16418197/80347405-e1208000-8831-11ea-9de3-440d88a9b567.png)

**Comment by aminya** [comment]
Now, we only use React inside atom-ide-base.
