### ISSUE TITLE
Datatip doesn't show (using python)

### ISSUE THREAD

**Issue by ghost** [atom-community/atom-ide-datatip#92]
<img width="1438" alt="Screen Shot 2020-07-21 at 3 20 19 PM" src="https://user-images.githubusercontent.com/61721397/88097127-b9f1fa00-cb65-11ea-9964-b7d910b8db06.png">

**Comment by ghost** [comment]
I am not sure if this was the problem but when I did Ctrl + Space it worked?

**Comment by aminya** [comment]
Sorry about the inconvenience. I fixed the issues. Please upgrade `atom-ide-markdown-service` and `atom-ide-datatips` to fix this.

**Comment by aminya** [comment]
@Ron-SK Please check and get back to me. I do not have a Python project to check, but I tested with two IDEs for other languages.

**Comment by aminya** [comment]
OK. I tested now. It seems to work. Let me know if you faced any other issues.

**Comment by ghost** [comment]
> OK. I tested now. It seems to work. Let me know if you faced any other issues.

Thank you so much! The ctrl-click didn't work and I wasn't sure whether this was a problem with the `ide-python` package or this package.

**Comment by ghost** [comment]
> @Ron-SK Please check and get back to me. I do not have a Python project to check, but I tested with two IDEs for other languages.

@aminya The datatips will only appear if I follow the atom-ide-markdown-service package's instructions, correct? I must edit the `package.json` file for it to work. Is `package.json` something I have to create or something that already exists (I am new to Atom editor, previous was VSCode but I prefer Atom for certain reasons).

**Comment by aminya** [comment]
You do not need to edit anything. That instruction is for the developers. Just update both packages.
